export const route = {
  home: '/',
  community: '/community',
  myPage: '/myPage',
  evaluate: '/evaluate',
  evaluateStart: '/evaluate/start',
  communityWrite: '/community/write',
  communityEdit: '/community/edit',
  communityDetail: '/community/detail',
  myEvaluate: '/myEvaluate',
  myInterview: '/myInterview',
  myInterviews: '/myInterviews',
  uploadDone: '/upload-done',
  uploadCheck: '/upload-check',
  questionLoading: '/question-loading',
  questionDone: '/question-done',
  mainAnswer: '/main-answer',
  feedbackResult: '/feedback-result',
};
